export const lorcanaCardImages = [
  require("../../assets/lorcanaCards/l1.png"),
  require("../../assets/lorcanaCards/l2.png"),
  require("../../assets/lorcanaCards/l3.png"),
  require("../../assets/lorcanaCards/l4.png"),
  require("../../assets/lorcanaCards/l5.png"),
  require("../../assets/lorcanaCards/l6.png"),
  require("../../assets/lorcanaCards/l7.png"),
  require("../../assets/lorcanaCards/l8.png"),
  require("../../assets/lorcanaCards/l9.png"),
  require("../../assets/lorcanaCards/l10.png"),
  require("../../assets/lorcanaCards/l11.png"),
  require("../../assets/lorcanaCards/l12.png"),
  require("../../assets/lorcanaCards/l13.png"),
] as const; 

export const pokemonCardImages = [
  require("../../assets/pokemonCards/p1.png"),
  require("../../assets/pokemonCards/p2.png"),
  require("../../assets/pokemonCards/p3.png"),
  require("../../assets/pokemonCards/p4.png"),
  require("../../assets/pokemonCards/p5.png"),
  require("../../assets/pokemonCards/p6.png"),
] as const;

export const riftboundCardImages = [
  require("../../assets/riftboundCards/r1.png"),
  require("../../assets/riftboundCards/r2.png"),
  require("../../assets/riftboundCards/r3.png"),
  require("../../assets/riftboundCards/r4.png"),
  require("../../assets/riftboundCards/r5.png"),
  require("../../assets/riftboundCards/r6.png"),
  require("../../assets/riftboundCards/r7.png"),
  require("../../assets/riftboundCards/r8.png"),
  require("../../assets/riftboundCards/r9.png"),
  require("../../assets/riftboundCards/r10.png"),
  require("../../assets/riftboundCards/r11.png"),
] as const;

export const shopCardImages = [
  require("../../assets/shopCards/s1.png"),
  require("../../assets/shopCards/s2.png"),
  require("../../assets/shopCards/s3.png"),
  require("../../assets/shopCards/s4.png"),
  require("../../assets/shopCards/s5.png"),
  require("../../assets/shopCards/s6.png"),
  require("../../assets/shopCards/s7.png"),
  require("../../assets/shopCards/s8.png"),
  require("../../assets/shopCards/s9.png"),
  require("../../assets/shopCards/s10.png"),
] as const;

export const yugiohCardImages = [
  require("../../assets/yugiohCards/y1.png"),
  require("../../assets/yugiohCards/y2.png"),
  require("../../assets/yugiohCards/y3.png"),
  require("../../assets/yugiohCards/y4.png"),
] as const;

export const magicCardImages = [
  require("../../assets/magicCards/m1.png"),
  require("../../assets/magicCards/m2.png"),
  require("../../assets/magicCards/m3.png"),
  require("../../assets/magicCards/m4.png"),
  require("../../assets/magicCards/m5.png"),
  require("../../assets/magicCards/m6.png"),
  require("../../assets/magicCards/m7.png"),
  require("../../assets/magicCards/m8.png"),
  require("../../assets/magicCards/m9.png"),
  require("../../assets/magicCards/m10.png"),
  require("../../assets/magicCards/m11.png"),
  require("../../assets/magicCards/m12.png"),
  require("../../assets/magicCards/m13.png"),
  require("../../assets/magicCards/m14.png"),
  require("../../assets/magicCards/m15.png"),
  require("../../assets/magicCards/m16.png"),
  require("../../assets/magicCards/m17.png"),
  require("../../assets/magicCards/m18.png"),
  require("../../assets/magicCards/m19.png"),
  require("../../assets/magicCards/m20.png"),
  require("../../assets/magicCards/m21.png"),
  require("../../assets/magicCards/m22.png"),
  require("../../assets/magicCards/m23.png"),
  require("../../assets/magicCards/m24.png"),
  require("../../assets/magicCards/m25.png"),
  require("../../assets/magicCards/m26.png"),
  require("../../assets/magicCards/m27.png"),
  require("../../assets/magicCards/m28.png"),
  require("../../assets/magicCards/m29.png"),
  require("../../assets/magicCards/m30.png"),
  require("../../assets/magicCards/m31.png"),
  require("../../assets/magicCards/m32.png"),
  require("../../assets/magicCards/m33.png"),
  require("../../assets/magicCards/m34.png"),
  require("../../assets/magicCards/m35.png"),
  require("../../assets/magicCards/m36.png"),
  require("../../assets/magicCards/m37.png"),
  require("../../assets/magicCards/m38.png"),
  require("../../assets/magicCards/m39.png"),
  require("../../assets/magicCards/m40.png"),
  require("../../assets/magicCards/m41.png"),
  require("../../assets/magicCards/m42.png"),
  require("../../assets/magicCards/m43.png"),
  require("../../assets/magicCards/m44.png"),
  require("../../assets/magicCards/m45.png"),
  require("../../assets/magicCards/m46.png"),
  require("../../assets/magicCards/m47.png"),
  require("../../assets/magicCards/m48.png"),
  require("../../assets/magicCards/m49.png"),
  require("../../assets/magicCards/m50.png"),
  require("../../assets/magicCards/m51.png"),
  require("../../assets/magicCards/m52.png"),
  require("../../assets/magicCards/m53.png"),
  require("../../assets/magicCards/m54.png"),
  require("../../assets/magicCards/m55.png"),
  require("../../assets/magicCards/m56.png"),
  require("../../assets/magicCards/m57.png"),
  require("../../assets/magicCards/m58.png"),
  require("../../assets/magicCards/m59.png"),
  require("../../assets/magicCards/m60.png"),
  require("../../assets/magicCards/m61.png"),
  require("../../assets/magicCards/m62.png"),
  require("../../assets/magicCards/m63.png"),
  require("../../assets/magicCards/m64.png"),
  require("../../assets/magicCards/m65.png"),
  require("../../assets/magicCards/m66.png"),
  require("../../assets/magicCards/m67.png"),
  require("../../assets/magicCards/m68.png"),
  require("../../assets/magicCards/m69.png"),
  require("../../assets/magicCards/m70.png"),
  require("../../assets/magicCards/m71.png"),
  require("../../assets/magicCards/m72.png"),
  require("../../assets/magicCards/m73.png"),
  require("../../assets/magicCards/m74.png"),
  require("../../assets/magicCards/m75.png"),
  require("../../assets/magicCards/m76.png"),
  require("../../assets/magicCards/m77.png"),
  require("../../assets/magicCards/m78.png"),
  require("../../assets/magicCards/m79.png"),
  require("../../assets/magicCards/m80.png"),
  require("../../assets/magicCards/m81.png"),
  require("../../assets/magicCards/m82.png"),
  require("../../assets/magicCards/m83.png"),
  require("../../assets/magicCards/m84.png"),
  require("../../assets/magicCards/m85.png"),
  require("../../assets/magicCards/m86.png"),
  require("../../assets/magicCards/m87.png"),
  require("../../assets/magicCards/m88.png"),
  require("../../assets/magicCards/m89.png"),
  require("../../assets/magicCards/m90.png"),
  require("../../assets/magicCards/m91.png"),
  require("../../assets/magicCards/m92.png"),
  require("../../assets/magicCards/m93.png"),
  require("../../assets/magicCards/m94.png"),
  require("../../assets/magicCards/m95.png"),
  require("../../assets/magicCards/m96.png"),
  require("../../assets/magicCards/m97.png"),
  require("../../assets/magicCards/m98.png"),
  require("../../assets/magicCards/m99.png"),
  require("../../assets/magicCards/m100.png"),
  require("../../assets/magicCards/m101.png"),
  require("../../assets/magicCards/m102.png"),
  require("../../assets/magicCards/m103.png"),
  require("../../assets/magicCards/m104.png"),
  require("../../assets/magicCards/m105.png"),
  require("../../assets/magicCards/m106.png"),
  require("../../assets/magicCards/m107.png"),
  require("../../assets/magicCards/m108.png"),
  require("../../assets/magicCards/m109.png"),
  require("../../assets/magicCards/m110.png"),
] as const;